#!/usr/bin/env python
from enum import Enum

VAL = Enum("VAL", "RIKSDAG REGION KOMMUN")

VAL_GEO = Enum("VAL_GEO", "RIKSDAGSVALKRETS LAN REGION REGIONVALKRETS KOMMUN KOMMUNVALKRETS VALDISTRIKT")

PARTI = Enum("PARTI", "M C L KD S V MP SD FI")
